title: Paul Robert Lloyd
short_title: PRL
description: Paul Robert Lloyd is an independent designer, writer and speaker based in Brighton, England.
url: https://paulrobertlloyd.com
theme_color: '#0055ff'
background_color: '#fafafa'
date_format: '%e %B %Y'

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  avatar: https://gravatar.com/avatar/15091a37bacfa4bdd011282627eaca2b?s=512

# Writing
kramdown:
  auto_id_stripping: true # This will become the default behaviour in kramdown 2.0
  footnote_backlink: '&#8617;&#xfe0e;'

# Publishing
source: ./src
destination: ./www
include: [_indices]
keep_files: [images]
profile: true

# Templates
liquid:
  error_mode: strict

# Collections
collections_dir: collections
collections:
  archives:
    output: true
  articles:
    output: true
  content:
    output: true
  discussions:
    output: true
  links:
    output: true
  notes:
    output: true
  posts:
    output: true
  projects:
    output: true
  talks:
    output: true

# Defaults
defaults:
  - scope:
      type: archives
    values:
      permalink: /:path/
      layout: archive-year
      regenerate: true

  - scope:
      type: articles
    values:
      permalink: /articles/:year/:month/:title
      layout: content

  - scope:
      type: content
    values:
      permalink: /:path
      layout: content

  - scope:
      type: discussions
    values:
      permalink: /:year/:month/:title/discussion
      layout: discussion

  - scope:
      type: links
    values:
      permalink: /links/:year/:month/:title
      layout: link
      feed: true
      archive: true

  - scope:
      type: notes
    values:
      permalink: /notes/:year/:month/:day-:hour:minute
      layout: note
      feed: true
      archive: true
      title: ''

  - scope:
      type: posts
    values:
      permalink: /:year/:month/:title
      layout: post
      feed: true
      archive: true
      image:
        preset: wide

  - scope:
      type: projects
    values:
      permalink: /projects/:title
      layout: project

  - scope:
      type: talks
    values:
      permalink: /talks/:year/:month/:title
      layout: talk
      archive: true

# Images
images:
  default:
    sources:
      - width: 1280 # Should match `image:` width used in JSON Feed
        quality: 90 # Should match `image:` quality used in JSON Feed
      - width: 800
        quality: 85
      - width: 640
        quality: 80
  thumbnail:
    sizes: '33vw'
    sources:
      - width: 320
        quality: 80
      - width: 240
        quality: 80
  supporting:
    sizes: '50vw'
    sources:
      - width: 960
        quality: 90
      - width: 640
        quality: 85
      - width: 480
        quality: 80
  showcase:
    sources:
      - width: 1280
        quality: 90
      - width: 1024
        quality: 85
      - width: 768
        quality: 80
  wide:
    sources:
      - width: 1280
        height: 675
        quality: 90
      - width: 1024
        height: 576
        quality: 85
      - width: 800
        height: 450
        quality: 80
  anamorphic:
    sources:
      - width: 1200
        height: 500
        quality: 90
      - width: 1020
        height: 425
        quality: 85
      - width: 720
        height: 300
        quality: 80

assets:
  source_maps: false

pagination:
  enabled: true
  title: ':title'
  permalink: '/page/:num.html'
  sort_reverse: true
  per_page: 12
