language: ruby
cache:
  bundler: true
  directories:
  - node_modules
rvm:
- 2.4.1
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
  - secure: Zt4dEuwZRPZ/X2pDXpNCj+R8+hvAeMfXDMICx2ueiXAuMjpKzxiJmGcXuS5IpAh8u2Ja0E/ER5pXyf2PgdqaWd5MbipclaOdR67+O6RmnvRCTVnwDTS5UvsLHmRwBjHH3WE5XQR15qUFXVRIgqPKBhblsP4bQM7ZUJjuDgee2F4=]
addons:
  ssh_known_hosts: <deploy-host>
script:
- "./bin/build"
before_deploy:
- openssl aes-256-cbc -K $encrypted_42ab359fa880_key -iv $encrypted_42ab359fa880_iv
  -in ./etc/ssl/travis-ci_rsa.enc -out /tmp/travis-ci_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis-ci_rsa
- ssh-add /tmp/travis-ci_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: "./bin/deploy"
  on:
    branch: master
