# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 10
paginate_path: /page/:num/

# Archives
archive:
  layout: index-archive
  title: :date

# Collections
collections:
  articles:
    output: true
    title: Articles
  essays:
    output: true
    title: Academic Essays
  presentations:
    output: true
    title: Presentations
  projects:
    output: true
    title: Projects

# Text formating
# Use kramdown with pygments (see: https://github.com/navarroj/krampygs)
# markdown: kramdown
# markdown_ext: krampygs
# highlighter: pygments

# Publishing
include: [_pages, .htaccess]
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, Plumbing.js README.md]

# Prose.io
prose:
  rooturl: _posts
  siteurl: http://paulrobertlloyd.com/
  media: 'assets/images/'
  metadata:
    _posts/articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "post-article"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "publication"
        field:
          element: "text"
          label: "Publication name"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link"
          placeholder: "http://"
    _posts/entries:
      - name: "layout"
        field:
          element: "hidden"
          value: "post-entry"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
    _posts/links:
      - name: "layout"
        field:
          element: "hidden"
          value: "post-link"
      - name: "link"
        field:
          element: "text"
          label: "Link"
          placeholder: "http://"
      - name: "embed"
        field:
          element: "checkbox"
          label: "Show as embed?"
          value: true
    _posts/photos:
      - name: "layout"
        field:
          element: "hidden"
          value: "post-photo"
      - name: "link"
        field:
          element: "text"
          label: "Link"
          placeholder: "http://"
      - name: "embed"
        field:
          element: "checkbox"
          label: "Show as embed?"
          value: true
    _posts/projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "post-project"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"