# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev:4000

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/
relative_permalinks: false

# Pagination
# paginate: 10
paginate_path: /page/:num/

# Archives
archive:
  layout: index-archive
  title: :date

# Text formating
# Use kramdown with pygments (see: https://github.com/navarroj/krampygs)
markdown: kramdown
markdown_ext: krampygs
pygments: true

# Publishing
# source:       /home/prlloyd/Dropbox/paulrobertlloyd.com/
# destination:  ../public/
include: ['_pages', .htaccess]
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, README.md]