# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/
relative_permalinks: false

# Pagination
# paginate: 10
paginate_path: /page/:num/

# Archives
archive:
  layout: index-archive
  title: :date

# Text formating
# Use kramdown with pygments (see: https://github.com/navarroj/krampygs)
markdown: kramdown
markdown_ext: krampygs
pygments: true

# Prose.io
prose:
  rooturl: _posts
  siteurl: http://paulrobertlloyd.com/
  media: 'assets/images/'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
    _posts/articles:
      - layout:
          element: "hidden"
          value: "post-article"
    _posts/entries:
      - layout:
          element: "hidden"
          value: "post-entry"
    _posts/links:
      - layout:
          element: "hidden"
          value: "post-link"
      - name: "link"
        field:
          element: "text"
          label: "Link"
          placeholder: "http://"
    _posts/photos:
      - layout:
          element: "hidden"
          value: "post-photo"
    _posts/projects:
      - layout:
          element: "hidden"
          value: "post-project"

# Publishing
# source:       /home/prlloyd/Dropbox/paulrobertlloyd.com/
# destination:  ../public/
include: [_pages, .htaccess]
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, README.md]