# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.com
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 12
paginate_path: /journal/:num/
paginate_exclude:
  categories: [essays, projects]

# Archives
archive:
  layout: archive
  title: :date

# Syntax highlighting (see: https://github.com/navarroj/krampygs)
markdown_ext: krampygs
highlighter: pygments

# Publishing
source: source
destination: public

# Gems
gems:
  - jekyll-sitemap