# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 10
paginate_path: /journal/:num/

# Archives
archive:
  layout: archive
  title: :date

# Syntax highlighting (see: https://github.com/navarroj/krampygs)
markdown_ext: krampygs, typogruby
highlighter: pygments

# Publishing
source: source
destination: public
include: [_pages, .htaccess] # TODO - Convert .htaccess into nginx rewrites

# Gems
gems:
  - jekyll-sitemap