# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/
relative_permalinks: false

# Pagination
# paginate: 10
paginate_path: /page/:num/

# Archives
archive:
  layout: index-archive
  title: :date

# Text formating
# Use kramdown with pygments (see: https://github.com/navarroj/krampygs)
markdown: kramdown
markdown_ext: krampygs
pygments: true

# Prose.io
prose:
  siteurl: http://paulrobertlloyd.com/
  rooturl: _posts
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
  media: 'assets/images/'
metadata:
  _posts:
    - name: "title"
      field:
        label: "Title"
        element: text
        placeholder: "Title of journal entry"

# Publishing
# source:       /home/prlloyd/Dropbox/paulrobertlloyd.com/
# destination:  ../public/
include: [_pages, .htaccess]
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, README.md]