# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.dev

# Gems
gems:
  - jekyll-sitemap

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
encoding: UTF-8

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 10
paginate_path: /journal/:num/

# Archives
archive:
  layout: archive
  title: :date

# Collections
collections:
  essays:
    output: true
    title: Academic Essays
  projects:
    output: true
    title: Projects

# Syntax highlighting (see: https://github.com/navarroj/krampygs)
markdown_ext: krampygs, typogruby
highlighter: pygments

# Publishing
include: [_pages, .htaccess]
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, Plumbing.js, README.md]