server:
  port: 18837
  instance_name: null
  timeout: 20000
  access_log_format: "combined"

test_server:
  enabled: false

cache:
  base_path: "tmp/converjon/cache"

download:
  url_whitelist:
    - "http://*.paulrobertlloyd.com/*"
  timeout: 5000

process:
  limit: 5
  timeout: 5000

analysis:
  aoi_name: "AOI"

cropping:
  default_mode: "aoi_emphasis"

logging:
  error: "stderr"
  debug: "stderr"
  access: "stdout"
