env: development
url: http://paulrobertlloyd.dev

# Assets
assets:
  gzip: false
  cache: ../.jekyll-assets-cache
  cachebust: none

# Picture
picture:
  converter: converjon
  cdn: http://images.paulrobertlloyd.dev
