url: http://paulrobertlloyd.dev
img_url: http://images.paulrobertlloyd.dev

# Remarks
remarks_dir: ../remarks

# Publishing
show_drafts: true

# Assets
assets:
  gzip: false
  cache: false
  cachebust: none
