production: false

# Image server
url: //paulrobertlloyd.dev
img_url: //images.paulrobertlloyd.dev

# Assets
assets:
  gzip: false
  cache: false
  cachebust: none

# Drafts
show_drafts: true

# Markup
kramdown:
  indent: 4
