env: production
url: https://paulrobertlloyd.com

# Assets
assets:
  gzip: false
  cache: ../.jekyll-assets-cache
  cachebust: hard

# Picture
picture:
  converter: thumbor
  key: '441922692530'
  cdn: https://analytics.paulrobertlloyd.com
