env: production
url: https://paulrobertlloyd.com

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# Assets
assets:
  gzip: false
  cache: ../.jekyll-assets-cache
  cachebust: hard
  js_compressor: uglifier

# Picture
picture:
  cdn_url: https://images.paulrobertlloyd.com
