title: Paul Robert Lloyd
encoding: UTF-8
theme-color: '#cc55cc'

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  photo: https://gravatar.com/avatar/15091a37bacfa4bdd011282627eaca2b?s=256

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title

# Pagination
paginate: 12
paginate_path: /journal/:num

# Writing
# See: https://github.com/jekyll/jekyll/issues/3371
kramdown:
  syntax_highlighter: rouge
  auto_id_stripping: true

# Collections
collections:
  content:
    output: true
    permalink: :path
  projects:
    output: true
  talks:
    output: true
  discussions:
    output: true

# Defaults
defaults:
  - scope:
      type: content
    values:
      layout: content

  - scope:
      type: posts
      path: '_posts/entries'
    values:
      layout: post-entry
      license:
        type: Creative Commons
        terms: BY-NC-SA
        description: 'You can republish this content without asking permission, but you must credit me (Paul Robert Lloyd) as the author and provide a link back to the original. You may not use any content for commercial purposes. If you make any changes, you must distribute these under the same license as the original.'
        url: http://creativecommons.org/licenses/by-nc-sa/4.0/

  - scope:
      type: posts
      path: '_posts/links'
    values:
      layout: post-link

  - scope:
      type: posts
      path: '_posts/galleries'
    values:
      layout: post-gallery
      theme: dark

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: talks
    values:
      layout: talk

  - scope:
      type: discussions
    values:
      layout: discussion

# Assets
assets:
  cache: .jekyll-assets-cache
  sources:
    - _assets/fonts
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vectors

# HTML Compression
compress_html:
  clippings: all

# Pictures
picture:
  markup: img
  source: /images
  presets:
    default:
      attr:
        class: c-picture c-picture--default
      source_medium:
        width: 800
      source_default:
        width: 480
    thumbnail:
      attr:
        class: c-picture c-picture--thumbnail
        sizes: '33vw'
      source_medium:
        width: 320
      source_default:
        width: 240
    supporting:
      attr:
        class: c-picture c-picture--supporting
        sizes: '50vw'
      source_medium:
        width: 640
      source_default:
        width: 480
    showcase:
      attr:
        class: c-picture c-picture--showcase
      source_large:
        width: 1024
        quality: 80
      source_medium:
        width: 768
      source_default:
        width: 480
    feature:
      attr:
        class: c-picture c-picture--feature
      source_xlarge:
        width: 1280
        height: 720
        quality: 88
      source_large:
        width: 1024
        height: 576
        quality: 88
      source_medium:
        width: 768
        height: 480
      source_default:
        width: 480
        height: 300

# Publishing
source: ./source
destination: ./public
exclude:
  - '**.scss'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: index-archive-year
    month: index-archive
    tag: index-archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html
