# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.com
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# License
license:
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-years
    month: archive
    tag: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tags/:name/'

# Remarks
remarks_dir: ../../../shared/remarks

# Syntax highlighting
highlighter: pygments

# Publishing
include: [_pages, essays/_pages]
source: ./source
destination: ./public

# Assets
asset_pipeline:
  output_path: assets/tmp

# Gems
gems:
  - jekyll-archives
  - jekyll-sitemap
