title: Paul Robert Lloyd
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  handle: "paulrobertlloyd"

# License
license:
  type: Creative Commons
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title.html

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Writing
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    inline_theme: github

# Assets
assets:
  sources:
    - _stylesheets
    - _javascripts
  css_compressor: sass

# Images
picture:
  source: _assets/images
  output: assets/images
  markup: img
  presets:
    default:
      attr:
        class: img img--default
      source_medium:
        width: 800
      source_default:
        width: 400
    thumbnail:
      attr:
        class: img img--thumbnail
        sizes: '33vw'
      source_medium:
        width: 400
      source_default:
        width: 200
    supporting:
      attr:
        class: img img--supporting
        sizes: '(min-width: 32em) 40vw, 100vw'
      source_medium:
        width: 800
      source_default:
        width: 400
    showcase:
      attr:
        class: img img--showcase
      source_large:
        width: 1200
      source_medium:
        width: 800
      source_default:
        width: 400

# Publishing
source: ./source
destination: ./public
include:
  - '**_pages'
exclude:
  - '**.scss'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive
    tag: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /topics/:name.html
