# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.com
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 12
paginate_path: /journal/:num/
paginate_exclude:
  categories: [projects]

# Archives
archive:
  layout: archive
  title: :date

# Remarks
remarks_dir: ../../../shared/remarks

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_permalink_style: pretty
ignored_tags: [Travel]

# Collections
collections:
  projects:
    output: true
    title: Projects
    permalink: /projects/:path/
  essays:
    output: true
    title: Academic Essays

# Syntax highlighting (see: https://github.com/navarroj/krampygs)
markdown_ext: krampygs
highlighter: pygments

# Publishing
include: [_pages]
source: ./source
destination: ./public

# Gems
gems:
  - jekyll-sitemap