title: Paul Robert Lloyd
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  url: http://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# License
license:
  type: Creative Commons
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title.html

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Writing
markdown: Pypedown # Pygments + Typograuby + kramdown

# Assets
assets:
  sources:
    - _stylesheets
    - _javascripts
  css_compressor: sass

# Publishing
source: ./source
destination: ./public
include:
  - '**_pages'
exclude:
  - '**.scss'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tag
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html
