title: Paul Robert Lloyd
encoding: UTF-8
theme:
  color: '#cc52cc'
  background-color: '#141214'

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  photo: https://gravatar.com/avatar/15091a37bacfa4bdd011282627eaca2b?s=256

# License (journal entries only)
license:
  type: Creative Commons
  terms: BY-NC-SA
  description: 'You can republish this content without asking permission, but you must credit me (Paul Robert Lloyd) as the author and provide a link back to the original. You may not use any content for commercial purposes. If you make any changes, you must distribute these under the same license as the original.'
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title

# Pagination
paginate: 12
paginate_path: /journal/:num

# Writing
kramdown:
# The auto_id_stripping option will be removed in kramdown 2.0 and become the default behaviour
  auto_id_stripping: true

# Collections
collections:
  content:
    output: true
    permalink: :path
  discussions:
    output: true
  galleries:
    output: true
    permalink: /:year/:month/:title
  projects:
    output: true
  talks:
    output: true

# Defaults
defaults:
  - scope:
      type: content
    values:
      layout: content

  - scope:
      type: discussions
    values:
      layout: discussion

  - scope:
      type: galleries
    values:
      layout: gallery
      theme: dark

  - scope:
      type: posts
    values:
      layout: entry

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: talks
    values:
      layout: talk

# Assets
assets:
  cache: false
  sources:
    - _assets/fonts
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vectors

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Pictures
picture:
# key: '441922692530'
  markup: img
  source: /images
  presets:
    default:
      attr:
        class: c-picture c-picture--default
      source_medium:
        width: 800
      source_default:
        width: 480
    thumbnail:
      attr:
        class: c-picture c-picture--thumbnail
        sizes: '33vw'
      source_medium:
        width: 320
      source_default:
        width: 240
    supporting:
      attr:
        class: c-picture c-picture--supporting
        sizes: '50vw'
      source_medium:
        width: 640
      source_default:
        width: 480
    showcase:
      attr:
        class: c-picture c-picture--showcase
      source_medium:
        width: 1024
      source_default:
        width: 768
    feature:
      attr:
        class: c-picture c-picture--feature
      source_large:
        width: 1280
        height: 720
        quality: 88
      source_medium:
        width: 1024
        height: 576
        quality: 88
      source_default:
        width: 768
        height: 480

# Publishing
source: ./source
destination: ./public
exclude:
  - '**.scss'

# Crossposting
jekyll-crosspost_to_medium:
  status: draft
  license: cc-40-by-nc-sa

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: index-archive-year
    month: index-archive
    tag: index-archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html
