title: Paul Robert Lloyd
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# License
license:
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Source code management
scm:
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title.html

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tag
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html

# Defaults
defaults:
  -
    scope:
      path: 'journal'
      type: 'posts'
    values:
      layout: 'entry'
  -
    scope:
      path: 'projects'
      type: 'posts'
    values:
      layout: 'project'
  -
    scope:
      path: 'essays'
      type: 'pages'
    values:
      layout: 'essay'

# Syntax highlighting
highlighter: pygments

# Publishing
source: ./source
destination: ./public
include:
  - _pages
  - essays/_pages

# Assets
assets:
  sources:
    - _stylesheets
    - _javascripts
  css_compressor: sass
  js_compressor: uglifier

# Gems
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-sitemap
