title: Paul Robert Lloyd
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  url: https://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com

# License
license:
  type: Creative Commons
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Source code management
scm:
  title: GitHub
  url: https://github.com/paulrobertlloyd/paulrobertlloyd.com

# Permalinks
permalink: /:year/:month/:title

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Writing
# See: https://github.com/jekyll/jekyll/issues/3371
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    inline_theme: github

# Assets
assets:
  sources:
    - assets/_fonts
    - assets/_icons
    - assets/_javascripts
    - assets/_stylesheets
    - assets/_vectors
  css_compressor: sass

# Pictures
picture:
  markup: img
  local_path: /assets/images
  presets:
    default:
      attr:
        class: img img--default
      source_medium:
        width: 800
      source_default:
        width: 480
    thumbnail:
      attr:
        class: img img--thumbnail
        sizes: '33vw'
      source_medium:
        width: 320
      source_default:
        width: 240
    supporting:
      attr:
        class: img img--supporting
        sizes: '(min-width: 32em) 40vw, 100vw'
      source_medium:
        width: 768
      source_default:
        width: 480
    showcase:
      attr:
        class: img img--showcase
      source_large:
        width: 1024
        quality: 70
      source_medium:
        width: 768
      source_default:
        width: 480
    feature:
      attr:
        class: img img--feature
      source_large:
        width: 1280
        height: 800
        quality: 70
      source_medium:
        width: 768
        height: 480
      source_default:
        width: 480
        height: 300

# Defaults
defaults:
  -
    scope:
      path: 'photos'
    values:
      theme: 'dark'

# Publishing
source: ./source
destination: ./public
include:
  - '**_pages'
exclude:
  - '**.scss'

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html
