title: Paul Robert Lloyd
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  email: noreply@paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# License
license:
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Permalinks
permalink: /:year/:month/:title.html

# Pagination
paginate: 12
paginate_path: /journal/:num/

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive
    month: archive
    tag: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html

# Defaults
defaults:
  -
    scope:
      path: 'journal'
      type: 'posts'
    values:
      layout: 'entry'
  -
    scope:
      path: 'projects'
      type: 'posts'
    values:
      layout: 'project'
  -
    scope:
      path: 'essays'
      type: 'pages'
    values:
      layout: 'essay'

# Syntax highlighting
highlighter: pygments
markdown_ext: foo

# HTML compression
compress_html:
  clippings: [body, head, article, section, p]
  endings: [li, dt, dd, p, thead, tbody, tr, td, th]

# Publishing
include:
  - _pages
  - essays/_pages
source: ./source
destination: ./public

# Assets
asset_pipeline:
  output_path: assets/tmp

# Gems
gems:
  - jekyll-archives
  - jekyll-sitemap
