# Setup
title: Paul Robert Lloyd
url: http://paulrobertlloyd.com
encoding: UTF-8

# Meta
author:
  name: Paul Robert Lloyd
  uri: http://paulrobertlloyd.com
  twitter: "@paulrobertlloyd"

# License
license:
  title: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/

# Permalinks
permalink: /:year/:month/:title/

# Pagination
paginate: 12
paginate_path: /journal/:num/

jekyll-archives:
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tags/:name/'
    category: '/category/:name/'

# Remarks
remarks_dir: ../../../shared/remarks

# Collections
collections:
  essays:
    output: true
    title: Academic Essays

# Syntax highlighting (see: https://github.com/navarroj/krampygs)
markdown_ext: krampygs
highlighter: pygments

# Publishing
include: [_pages]
source: ./source
destination: ./public

# Gems
gems:
  - jekyll-archives
  - jekyll-sitemap
