- title: 'Design'
  description: 'I believe that by developing common design and interaction patterns, we can combine the systems of the web and graphic design to great effect. I value cohesiveness and attention to detail, and designing products that can be used by all.'

- title: 'Front-end development'
  description: 'I employ pragmatic front-end architecture practices that progressively enhance semantic HTML with modular CSS and unobtrusive JavaScript. I advocate tools like style guides and pattern portfolios that encourage collaboration within teams.'

- title: 'Writing and speaking'
  description: 'I like to share accumulated knowledge with my peers, and have written articles for publications like net Magazine, A List Apart and 24 ways. I have also spoken at design conferences around the UK and Europe.'
