exclude:
  - '../../source/_assets/stylesheets/vendor/**'
  - '../../source/_assets/javascripts/vendor/**'

linters:
  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  ImportantRule:
    enabled: true
    exclude:
      - '../../source/_assets/stylesheets/helpers/*.scss'
      - '../../source/_assets/stylesheets/utilities/*.scss'

  Indentation:
    enabled: true
    character: space
    width: 4

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true
    force_nesting: false

  NameFormat:
    enabled: false
    convention: BEM

  NestingDepth:
    enabled: true
    max_depth: 2
    exclude:
      - '../../source/_assets/stylesheets/scopes/*.scss'
      - '../../source/_assets/stylesheets/themes/*.scss'

  PropertySortOrder:
    enabled: true
    order: concentric
    ignore_unspecified: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true

  SelectorDepth:
    enabled: true
    max_depth: 2
    exclude:
      - '../../source/_assets/stylesheets/scopes/*.scss'
      - '../../source/_assets/stylesheets/themes/*.scss'

  SelectorFormat:
    enabled: false
    convention: BEM

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true
