exclude:
  - '../../source/_assets/stylesheets/vendor/**'
  - '../../source/_assets/javascripts/vendor/**'

linters:
  Comment:
    enabled: false

  Indentation:
    enabled: true
    character: space
    width: 4

  LeadingZero:
    enabled: true
    style: include_zero

  NameFormat:
    enabled: false
    convention: BEM

  PropertySortOrder:
    enabled: true
    order: concentric
    ignore_unspecified: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true

  SelectorDepth:
    enabled: true
    exclude:
      - '../../source/_assets/stylesheets/scopes/**'
    max_depth: 3

  SelectorFormat:
    enabled: false
    convention: BEM

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true
